name: release
on:
  workflow_dispatch: # Only manual trigger and only for the main branch
    branches:
    - main
    inputs:
      bump_level:
        type: choice
        description: Select bump level
        required: true
        options:
        - patch
        - minor
        - major

permissions:
  contents: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release       # needed for PyPI OIDC

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_TOKEN_DANIEL}}

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install UV
      run: |
         curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Build and publish
      run: |
        set -euv
        
        BUMP_LEVEL=${{ github.event.inputs.bump_level }}
        echo "bump level: ${BUMP_LEVEL}"
        git config --local user.email "Bumpversion"
        git config --local user.name "Bumpversion"

        # Version bump
        uv version --bump ${BUMP_LEVEL}
        NEW_VERSION=$(uv version --short)
        echo ${NEW_VERSION}
        git add pyproject.toml uv.lock
        git commit -m "Bump version to ${NEW_VERSION}"
        git tag "v${NEW_VERSION}"

        git push -f  
        git push --tags -f
        
        uv build
        
        echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

    - uses: pypa/gh-action-pypi-publish@release/v1    # publish
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.NEW_VERSION }}
        release_name: v${{ env.NEW_VERSION }}
        body: |
          pypi package: https://pypi.org/project/dltlint/${{ env.NEW_VERSION }}/
        draft: false
        prerelease: false
